AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

src/Microsoft.IdentityModel.Logging/Microsoft.IdentityModel.Logging.xproj, src/Microsoft.IdentityModel.Logging/Properties/AssemblyInfo.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/106%23issuecomment-84196692%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/106%23issuecomment-84196692%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40tushargupta51__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20In%20order%20for%20us%20to%20evaluate%20and%20accept%20your%20PR% …
=> Adding assemblyInfo.cs

src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocol.Extensions/project.json, src/System.IdentityModel.Tokens/project.json
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/107%23issuecomment-85827522%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/107%23issuecomment-85827522%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40tushargupta51__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20In%20order%20for%20us%20to%20evaluate%20and%20accept%20your%20PR% …
=> Updating version from beta1 to beta4

src/System.IdentityModel.Tokens/Jwt/JwtSecurityToken.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/tushargupta51%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/108%23issuecomment-86264856%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-03-26T00%3A30%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A% …
=> Git issue 103.

Wilson.sln, src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs, src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocol.Extensions/project.json, src/System.IdentityModel.Tokens/Jwt/JwtSecurityToken.cs, src/System.IdentityModel.Tokens/Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens/Validators.cs, src/System.IdentityModel.Tokens/project.json, tests/Microsoft.IdentityModel.Logging.Tests/LoggerTests.cs, tests/Microsoft.IdentityModel.Logging.Tests/project.json, tests/Microsoft.IdentityModel.Protocol.Extensions.Tests/project.json, tests/System.IdentityModel.Tokens.Tests/project.json
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/111%23issuecomment-87947614%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/111%23issuecomment-87947614%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40tushargupta51__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3EYou%27ve%20already%20signed%20the%20contribution%20license%20agreement.%20Thanks%21%3C/span%3E%5C …
=> Updating project.json versions and renaming WilsonEventSource to IdentityModelEventSource

src/Microsoft.IdentityModel.Protocol.Extensions/Configuration/HttpDocumentRetriever.cs, src/Microsoft.IdentityModel.Protocol.Extensions/OpenIdConnectMessage.cs
OpenIdConnectMessage ctor checks for key null or empty before passing.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/tushargupta51%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/114%23issuecomment-91353534%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-09T20%3A53%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20 …
=> set ConfigureAwait(false) to avoid deadlock.

src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/System.IdentityModel.Tokens/Jwt/JwtSecurityToken.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/119%23issuecomment-91673747%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/119%23issuecomment-91673747%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40tushargupta51__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3EYou%27ve%20already%20signed%20the%20contribution%20license%20agreement.%20Thanks%21%3C/span%3E%5C …
=> Fixing an exception issue in loghelper

src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/System.IdentityModel.Tokens/Jwt/JwtSecurityToken.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/118%23issuecomment-91672067%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/118%23issuecomment-91672067%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40tushargupta51__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3EYou%27ve%20already%20signed%20the%20contribution%20license%20agreement.%20Thanks%21%3C/span%3E%5C …
=> Fixing exception issue in loghelper

src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs, tests/Shared/ClaimSets.cs, tests/Shared/IdentityComparer.cs, tests/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
Fixed role mapping in 4.x
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/124?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/124'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Issue: #122

src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/System.IdentityModel.Tokens/ClaimTypeMapping.cs, tests/Microsoft.IdentityModel.Protocol.Extensions.Tests/project.json, tests/Shared/ClaimSets.cs, tests/Shared/ExpectedException.cs, tests/Shared/IdentityComparer.cs, tests/System.IdentityModel.Tokens.Tests/CreateAndValidateTokens.cs, tests/System.IdentityModel.Tokens.Tests/project.json
Issues #127 #122
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/139%23issuecomment-95371737%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/139%23issuecomment-95371737%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40tushargupta51__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3EYou%27ve%20already%20signed%20the%20contribution%20license%20agreement.%20Thanks …
=> Fixes for log helper and "roles" mapping issues

src/common/ErrorMessages.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/144%23issuecomment-96366674%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/144%23issuecomment-96366674%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40LeviBotelho__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribut …
=> Fix 'endcoded' error message typo

src/Microsoft.IdentityModel.Protocol.Extensions/OpenIdConnectConstants.cs
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/147?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/147'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Adding constant for code only response type

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
found while diagnosing a bug.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/160%23issuecomment-105977634%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/160%23issuecomment-105977634%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40ryan1234__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3EYou%27ve%20already%20signed%20the%20contribution%20license%20agreement …
=> spelling mistake.

NuGet.Config, src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs, src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/Microsoft.IdentityModel.Protocol.Extensions/OpenIdConnectConstants.cs, src/System.IdentityModel.Tokens/Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens/Validators.cs
#156, #156, #158, #159, #162
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/165%23issuecomment-106097706%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/165%23issuecomment-106097706%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20could%20you%20please%20review%20this%3F%22%2C%20%22created_at%22%3A%20%222015-05-27T22%3A27%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20%22t …
=> Fixing multiple github issues

src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs, src/Microsoft.IdentityModel.Logging/project.json
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/169%23discussion_r31271639%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%209a2bdfe201f7923666f1ce1205feaa9a2917edf0%20src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs%204%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/169%23discussion_r31271639%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20guess%20we%20don%27t%20need%20the%20%5BNonEvent%5D%20attribute%20on%20the%20statics%3F%22%2C%20%22created_at%22%3A%20%222015-05-28T20%3A00%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/317 …
=> moving system packages to aspnetcore50 and fixing tests for logging

NuGet.Config
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/170%23issuecomment-106606910%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/170%23issuecomment-106606910%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22We%20need%20this%20because%20we%20use%20KoreBuild%22%2C%20%22created_at%22%3A%20%222015-05-28T21%3A35%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3172421%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/brentschmaltz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22% …
=> Reverting the nuget feed from dotnetcore to aspnetvnext

test/System.IdentityModel.Tokens.Tests/Properties/AssemblyInfo.cs
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/171?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/171'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Changes to AssemblyInfo.cs to make tests run sequentially

test/System.IdentityModel.Tokens.Tests/project.json
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/172?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/172'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Removing beta 4 in the version name from project.json.

CHANGELOG.md
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/173%23issuecomment-108072164%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/173%23issuecomment-108072164%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20Can%20you%20take%20a%20look%3F%22%2C%20%22created_at%22%3A%20%222015-06-02T19%3A40%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7 …
=> Updating changelog.md

test/Microsoft.IdentityModel.Tokens.Jwt.Tests/Properties/AssemblyInfo.cs, test/Microsoft.IdentityModel.Tokens.Tests/Properties/AssemblyInfo.cs
#189
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/190?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/190'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> adding attribute in assemblyInfo.cs to make tests run sequentially

src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocols.WsFederation/project.json, src/Microsoft.IdentityModel.Protocols/project.json, src/Microsoft.IdentityModel.Tokens.Jwt/project.json, src/Microsoft.IdentityModel.Tokens.Saml/project.json, src/Microsoft.IdentityModel.Tokens/project.json
#167
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/199%23issuecomment-121181407%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/199%23discussion_r34612889%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/199%23issuecomment-121181407%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Testing%3A%20Created%20a%204.5.1%20.Net%20application%2C%20added%20references%20to%205.x%20wilson%20packages%2C%20validated%20that%20configuration%20retrieval%20and%20token%20validation%20works.%22%2C%20%22c …
=> adding net451 target in projet.json

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/Properties/AssemblyInfo.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/204%23issuecomment-126129339%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/204%23issuecomment-126129339%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20I%20am%20merging%20this%20to%20push%20a%20build%20on%20myget.%20It%20fixes%20the%20assemblyInfo%20version.%22%2C%20%22created_at%22%3A%20%222015-07-29T23%3A43%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.c …
=> fixing assemblyInfo version in assebmlyInfo.cs for oidc and wsfed

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs, src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs, src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens/ErrorMessages.cs, src/System.IdentityModel.Tokens/Exceptions/SecurityTokenInvalidSigningKeyException.cs, src/System.IdentityModel.Tokens/TokenValidationParameters.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMessageTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs, test/System.IdentityModel.Tokens.Tests/ExpectedException.cs
Fixes #184 #137 #206  #174
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/207%23issuecomment-127721811%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/207%23issuecomment-128125047%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/207%23discussion_r36345000%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/100b790566fcccf53d8bc5fada2ae16e69ae9dc1%23commitcomment-12475874%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-ident …
=> Beta7 fixes

src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs, test/System.IdentityModel.Tokens.Tests/ClaimSets.cs
Makes claim mapping and filtering in `JwtSecurityTokenHandler` a feature on a per instance basis.
Summary:
- Adds public properties on instances of `JwtSecurityTokenHandler`.
- `InstanceInboundClaimTypeMap`
- `InstanceOutboundClaimTypeMap`
- `InstanceInboundClaimFilter`
- Pulls outbound claim type mapping from the `JwtPayload` class, it's now done in the handler.
- Test added for exercising these new features.
So, as requested in #95, here you go. I hope this is a good start that can be shaped into a final api for these features.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/208%23issuecomment-127783346%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identit …
=> Jwt claim mapping

build.cmd
#244
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/245%23issuecomment-139648248%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/245%23issuecomment-139651080%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/245%23issuecomment-139648248%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40RandalliLama%20%22%2C%20%22created_at%22%3A%20%222015-09-11T20%3A02%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url …
=> removing the hardcoded Sake version from build.cmd

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/JsonConstants.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/JsonWebKey.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/JsonWebKeySet.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs, src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs, src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs, src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/ConfigurationManagerTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/ExtensibilityTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JsonExtensionsTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtDerivedTestTypes.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
#237 : adding tests for strict json parsing
#210: implementing resolveIssuerSigningKey
#234 : moving json files to OIDC project
#47 : removing the "auth_time" claim mapping and changing its type to int32
#242: changing the type of amr from string to array of strings.
#253 adding inner exception in cofigurationmanager.getconfigurationasyn
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/252%23issuecomment-142451164%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/252%23issuecomment-142735544%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/5e99c259972621f59adbaacf9b39 …
=> Beta8 fixes

NuGet.Config
Fixes #268
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/269%23issuecomment-146344789%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/269%23issuecomment-146386378%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/269%23issuecomment-146344789%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20%22%2C%20%22created_at%22%3A%20%222015-10-07T21%3A57%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22h …
=> adding dotnet-core feed in nuget.config

test/Microsoft.IdentityModel.Logging.Tests/LoggerTests.cs, test/Microsoft.IdentityModel.Logging.Tests/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json, test/Microsoft.IdentityModel.Protocols.Tests/project.json, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/project.json, test/System.IdentityModel.Tokens.Jwt.Tests/project.json, test/System.IdentityModel.Tokens.Saml.Tests/project.json, test/System.IdentityModel.Tokens.Tests/DerivedTypes.cs, test/System.IdentityModel.Tokens.Tests/IdentityUtilities.cs, test/System.IdentityModel.Tokens.Tests/project.json
#257
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/272%23issuecomment-146570953%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/272%23issuecomment-146669548%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/272%23issuecomment-146924005%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/272%23issuecomment-146570953%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20%22%2C%20%22created_at%22%3A%20%222015-10-08T14%3A56%3 …
=> Dnxcore50tests

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/284?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/284'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Issue: #283, not reading JWT tokens correctly.

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/LogMessages.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs, test/System.IdentityModel.Tokens.Tests/IdentityComparer.cs, test/System.IdentityModel.Tokens.Tests/TokenValidationParametersTests.cs
#77 #87
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/287%23issuecomment-148633066%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/287%23issuecomment-148798428%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/287%23issuecomment-148633066%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20%22%2C%20%22created_at%22%3A%20%222015-10-16T07%3A00%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html …
=> fixing tests

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/292?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/292'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> fix openidconnectmessage dependency

src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/project.json, src/Microsoft.IdentityModel.Protocols.WsFederation/project.json, src/Microsoft.IdentityModel.Protocols/project.json, src/System.IdentityModel.Tokens.Jwt/project.json, src/System.IdentityModel.Tokens.Saml/project.json, src/System.IdentityModel.Tokens/project.json
=> delay signing the assemblies

test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
=> Set 'iat' claim. Fixes test failure.

test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
#323 was not completely fixed. The test was still failing. Couple of places were missed where 'issuedAt' needs to be added.
=> specify IssuedAt property

src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs
=> disposing httpClient in HttpDocumentRetriever.cs

src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.Tokens.Tests/TokenValidationParametersTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
=> Remove validateSignature flag and make ResolveAsymmetricAlgorithm extensible

NuGet.Config, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/project.json, test/Microsoft.IdentityModel.Tokens.Tests/project.json
=> use rsa.Create()

src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/project.json, src/Microsoft.IdentityModel.Protocols.WsFederation/project.json, src/Microsoft.IdentityModel.Protocols/project.json, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/Utility.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, src/Microsoft.IdentityModel.Tokens/project.json, src/System.IdentityModel.Tokens.Jwt/project.json, src/System.IdentityModel.Tokens.Saml/project.json, test/Microsoft.IdentityModel.Logging.Tests/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json, test/Microsoft.IdentityModel.Protocols.Tests/project.json, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/project.json, test/Microsoft.IdentityModel.Tokens.Tests/IdentityUtilities.cs, test/Microsoft.IdentityModel.Tokens.Tests/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/RsaSecurityKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/project.json, test/System.IdentityModel.Tokens.Jwt.Tests/project.json, test/System.IdentityModel.Tokens.Saml.Tests/project.json
=> updating to use TFM

src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/project.json, src/Microsoft.IdentityModel.Protocols.WsFederation/project.json, src/Microsoft.IdentityModel.Protocols/project.json, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/Utility.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, src/Microsoft.IdentityModel.Tokens/project.json, src/System.IdentityModel.Tokens.Jwt/project.json, src/System.IdentityModel.Tokens.Saml/project.json, test/Microsoft.IdentityModel.Logging.Tests/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json, test/Microsoft.IdentityModel.Protocols.Tests/project.json, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/project.json, test/Microsoft.IdentityModel.Tokens.Tests/project.json, test/System.IdentityModel.Tokens.Jwt.Tests/project.json, test/System.IdentityModel.Tokens.Saml.Tests/project.json
dnx451 -> net451 in test.
netstandard1.3, dotnet5.4 -> netstandard1.4, dotnet5.5 in src.
To be in sync with asp.net
Updated versions of System* assemblies.
Removed dependencies: System.Security.Principal, System.Security.Cryptography.OpenSsl
Update Newtonsoft.Json -> 8.0.3
#354 
#350
=> Update to get in sync with asp.net RC2

src/Microsoft.IdentityModel.Logging/LogHelper.cs
Add comments for EventLevel
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/384
=> Add comment for default EventLevel

src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.Tokens.Tests/DerivedTypes.cs, test/Microsoft.IdentityModel.Tokens.Tests/ECDsaSecurityKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/RsaSecurityKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/X509SecurityKeyTests.cs
=> Moving IsSupportedAlgorithm api from SignatureProvider to SecurityKey

src/System.IdentityModel.Tokens.Jwt/project.json
@brentschmaltz @tushargupta51 @ChenYan98 
Fixing a small typo in the nuget package description as my first Wilson checkin!
=> Fix typo in NuGet package description

src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs
For #401. @brentschmaltz , please take a look.
=> Update default automatic MetadataRefresh to 1 day.

src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs
@PinpointTownes noticed that the comment wasn't updated for the new refresh interval; fixing that issue.
=> Update comment for updated Default Automatic Refresh interval.

CONTRIBUTING.md, README.md
@tushargupta51 @brentschmaltz @bgever
I added a CONTRIBUTING.md with branch, build, test, and contribution information. I added a link to it in the readme.md. This will go into master so it's on the repo landing page. This addresses #402.
When we create new branches, we'll need to make sure to keep this up to date.
=> Add branch and release guidance in contributing.md

src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs
@tushargupta51 @ChenYan98 
Fixing the </param> issue that broke last night's build.
=> Fix build break in XML comments

src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSignatureProvider.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
=> Fix setting CPF.Default, clean up exceptions

src/common/ErrorMessages.cs
To be consistent with error message IDX10205, as described in issue #426.
=> Remove double space in error message IDX10214

src/Microsoft.IdentityModel.Tokens/project.json, test/Microsoft.IdentityModel.Tokens.Tests/project.json
aspnet wants us to upgrade to this version of newtonsoft
=> updated newtonsoft to 9.0.1-beta1

build.ps1
=> Add serviceability flag to nuget packages

src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/SigningCredentials.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/LogMessages.cs, test/Microsoft.IdentityModel.Tokens.Tests/CryptoExtensibilityTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/DerivedTypes.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityUtilities.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenTests.cs
Release SignatureProvider
Remove SecurityKey.GetSignatureProvider
=> Don't set securityKey.CryptoFactory in JwtSecurityTokenHandler

src/System.IdentityModel.Tokens.Jwt/JsonClaimValueTypes.cs, src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs
=> adding support for claims with null values

src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
Added tests for round tripping JwtSecurityToken and JwtHeader.
=> Create Default map and assign in JwtHeader

src/Microsoft.IdentityModel.Protocol.Extensions/Configuration/ConfigurationManager.cs
=> Add ConfigureAwait for await to avoid deadlock

build.ps1, buildConfiguration.xml, test/Microsoft.IdentityModel.Logging.Tests/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json, test/Microsoft.IdentityModel.Protocols.Tests/project.json, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/project.json, test/Microsoft.IdentityModel.Tokens.Tests/project.json, test/System.IdentityModel.Tokens.Jwt.Tests/project.json, test/System.IdentityModel.Tokens.Saml.Tests/project.json
=> Update the .NET CLR and CLI versions to the escrow builds

build.ps1, buildConfiguration.xml, src/Microsoft.IdentityModel.Tokens/project.json, test/Microsoft.IdentityModel.Logging.Tests/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/project.json, test/Microsoft.IdentityModel.Protocols.Tests/project.json, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/project.json, test/Microsoft.IdentityModel.Tokens.Tests/project.json, test/System.IdentityModel.Tokens.Jwt.Tests/project.json, test/System.IdentityModel.Tokens.Saml.Tests/project.json
Update newtonsoft and .net core app and corefx versions
=> Update dependencies version

buildConfiguration.xml
cli downloads url and version needs updating
=> Update url and version for cli

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, tests/Microsoft.IdentityModel.Protocol.Extensions.Tests/CrossTokenTests.cs, tests/Shared/IdentityUtilities.cs
=> User control over nbf and expires

test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs
=> Test how we handle unicode mapping

src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeyECTypes.cs
=> Update JsonWebKeyECTypes.P512 to P521 without breaking changes

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
For this type of issue, we had to make a choice between compile time break or runtime.
We choose to live with a compile time break.
=> Add new API

test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
Used TheoryData to make it easier to isolate a specific test failure.
=> Factored out test cases

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs
=> Set "RequireSub" to true by default

build.ps1
This will keep the build from succeeding when unit tests fail.
=> Fail build if unit tests fail

src/System.IdentityModel.Tokens.Jwt/Validators.cs, src/common/ErrorMessages.cs, tests/System.IdentityModel.Tokens.Jwt.Tests/ValidatorsTests.cs
=> Implement Validators.ValidateIssuerSecurityKey

NuGet.Config, build/commonTest.props, src/Microsoft.IdentityModel.Logging/Microsoft.IdentityModel.Logging.csproj, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.csproj, src/Microsoft.IdentityModel.Protocols.WsFederation/Microsoft.IdentityModel.Protocols.WsFederation.csproj, src/Microsoft.IdentityModel.Protocols/Microsoft.IdentityModel.Protocols.csproj, src/Microsoft.IdentityModel.Tokens.Saml/Microsoft.IdentityModel.Tokens.Saml.csproj, src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj, src/Microsoft.IdentityModel.Xml/Microsoft.IdentityModel.Xml.csproj, src/System.IdentityModel.Tokens.Jwt/System.IdentityModel.Tokens.Jwt.csproj, test/Microsoft.IdentityModel.Logging.Tests/Microsoft.IdentityModel.Logging.Tests.csproj, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests.csproj, test/Microsoft.IdentityModel.Protocols.Tests/Microsoft.IdentityModel.Protocols.Tests.csproj, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/Microsoft.IdentityModel.Protocols.WsFederation.Tests.csproj, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationConfigurationRetrieverTests.cs, test/Microsoft.IdentityModel.Tests/Comparer.cs, test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tests/IdentityUtilities.cs, test/Microsoft.IdentityModel.Tests/Microsoft.IdentityModel.Tests.csproj, test/Microsoft.IdentityModel.Tests/ReferenceMetadata.cs, test/Microsoft.IdentityModel.Tests/ReferenceXml.cs, test/Microsoft.IdentityModel.Tests/TestSets.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Microsoft.IdentityModel.Tokens.Saml.Tests.csproj, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/Microsoft.IdentityModel.Tokens.Tests.csproj, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs, test/Microsoft.IdentityModel.Xml.Tests/DsigTests.cs, test/Microsoft.IdentityModel.Xml.Tests/Microsoft.IdentityModel.Xml.Tests.csproj, test/System.IdentityModel.Tokens.Jwt.Tests/System.IdentityModel.Tokens.Jwt.Tests.csproj
Updated tests to use netcore 2.0, saml, wsfed, xml tests running against net1.4
=> Use netcoreapp2.0 for tests

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectScope.cs
Added offline_access and email claims.
=>  Issue #589 add offline_access and email claims

src/Microsoft.IdentityModel.Tokens.Saml/Saml/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlAdvice.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlEvidence.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSerializer.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tests/ReferenceSaml.cs, test/Microsoft.IdentityModel.Tests/ReferenceXml.cs, test/Microsoft.IdentityModel.Tests/TestSets.cs, test/Microsoft.IdentityModel.Tests/XmlGenerator.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSerializerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlTheoryData.cs
=> Add SamlSerializerTests test cases

test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityComparerTests.cs
=> Added in tests for types compared in the IdentityComparer.

src/Microsoft.IdentityModel.Protocols.WsFederation/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/SecurityTokenServiceTypeRoleDescriptor.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMetadataSerializer.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationConfigurationRetrieverTests.cs
Moved TheoryData below test case, and changed the method in WsFederationMetadataSerializer.
=> Issue #678 and #677

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlConstants.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSerializer.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, test/CrossVersionTokenValidation.Tests/CrossVersionTokenValidation.Tests.csproj, test/CrossVersionTokenValidation.Tests/SamlCrossVersionTokenValidationTests.cs, test/Microsoft.IdentityModel.Protocol.Extensions.4x/CrossVersionTokenValidationTestsData.cs, test/Microsoft.IdentityModel.Protocol.Extensions.4x/Microsoft.IdentityModel.Protocol.Extensions.OldVersion.csproj, test/Microsoft.IdentityModel.Tests/ClaimSets.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tests/ReferenceSaml.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSerializerTests.cs
=> Add CreateClaimsPrincipalCrossVersionTest test case

src/Microsoft.IdentityModel.Logging/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/LogMessages.cs, src/Microsoft.IdentityModel.Protocols/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/Xml/LogMessages.cs, src/Microsoft.IdentityModel.Xml/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/LogMessages.cs
=> Removed unnecessary messages from LogMessages.cs

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenHandlerTests.cs
=> fix for #744 and #743

src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs
=> Fix capitalization of acronym

build/common.props, build/commonTest.props, src/Microsoft.IdentityModel.Logging/Microsoft.IdentityModel.Logging.csproj, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.csproj, src/Microsoft.IdentityModel.Protocols.WsFederation/Microsoft.IdentityModel.Protocols.WsFederation.csproj, src/Microsoft.IdentityModel.Protocols/Microsoft.IdentityModel.Protocols.csproj, src/Microsoft.IdentityModel.Tokens.Saml/Microsoft.IdentityModel.Tokens.Saml.csproj, src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj, src/Microsoft.IdentityModel.Xml/Microsoft.IdentityModel.Xml.csproj, src/System.IdentityModel.Tokens.Jwt/System.IdentityModel.Tokens.Jwt.csproj
NuGet packages now contain a link to the GitHub repository as well as relevant tags.
=> Added in additional info for NuGet packages

src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, src/Microsoft.IdentityModel.Xml/KeyInfo.cs, src/Microsoft.IdentityModel.Xml/RSAKeyValue.cs, src/Microsoft.IdentityModel.Xml/XmlSignatureConstants.cs, test/Microsoft.IdentityModel.Tests/TestSets.cs, test/Microsoft.IdentityModel.Xml.Tests/DSigSerializerTests.cs, test/Microsoft.IdentityModel.Xml.Tests/KeyInfoTests.cs
Fixes #719.
KeyInfo now has an RSAKeyValue property. The ReadKeyInfo() method of DSigSerializer has also been modified to support this change.
=> Added support for RSAKeyValue

src/Microsoft.IdentityModel.Tokens/AsymmetricSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.Tests/DerivedTypes.cs, test/Microsoft.IdentityModel.Tokens.Tests/ECDsaSecurityKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/RsaSecurityKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
=> Issue #480 fix hasPrivateKey issue

src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMetadataSerializer.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSubject.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, src/Microsoft.IdentityModel.Xml/IssuerSerial.cs, src/Microsoft.IdentityModel.Xml/KeyInfo.cs, src/Microsoft.IdentityModel.Xml/LogMessages.cs, src/Microsoft.IdentityModel.Xml/X509Data.cs, src/Microsoft.IdentityModel.Xml/XmlSignatureConstants.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationConfigurationRetrieverTests.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tests/ReferenceMetadata.cs, test/Microsoft.IdentityModel.Tests/TestSets.cs, test/Microsoft.IdentityModel.Tests/XmlGenerator.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityComparerTests.cs, test/Microsoft.IdentityModel.Xml.Tests/DSigSerializerTests.cs, test/Microsoft.IdentityModel.Xml.Tests/KeyInfoTests.cs
Fixes #777. 
Also addresses #768.
=> Modified the KeyInfo class so that it better represents the structure of the DSig KeyInfo element

src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/Properties/AssemblyInfo.cs
=> Made M.IM.Tokens.LogMessages internal

test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenHandlerTests.cs
=> Added in round trip token tests for JsonWebKey and RsaSecurityKey

src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMetadataSerializer.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSerializer.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2AuthorizationDecisionStatement.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2Serializer.cs, src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationConfigurationRetrieverTests.cs, test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tests/ReferenceMetadata.cs, test/Microsoft.IdentityModel.Tests/ReferenceSaml.cs, test/Microsoft.IdentityModel.Tests/TestSets.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SerializerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2TheoryData.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSerializerTests.cs, test/Microsoft.IdentityModel.Xml.Tests/DSigSerializerTests.cs
=> Added in empty element checks and tests for SamlSerializer, Saml2Serializer, and DSigSerializer

src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
=> Added exceptions thrown from subroutines into the xml documentation comments of ValidateToken()

src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, test/Microsoft.IdentityModel.Tests/TestSets.cs, test/Microsoft.IdentityModel.Xml.Tests/DSigSerializerTests.cs
=> Added in write tests for SignedInfo and Signature

build.ps1
=> Added in the symbols option for the pack command

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeyConverter.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, src/Microsoft.IdentityModel.Xml/X509Data.cs, src/System.IdentityModel.Tokens.Jwt/JsonExtensions.cs, src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenTests.cs
=> Made sure that all ArgumentNullExceptions are thrown through the use of LogHelper

src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/Microsoft.IdentityModel.Logging/TextWriterEventListener.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMetadataSerializer.cs, src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs, src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, src/Microsoft.IdentityModel.Tokens/Validators.cs, src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
=> Replaced all instances of IMEventSource.Logger.WriteInformation with LogHelper.LogInformation

buildConfiguration.xml, src/Microsoft.IdentityModel.Logging/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/project.json, src/Microsoft.IdentityModel.Protocols.WsFederation/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/project.json, src/Microsoft.IdentityModel.Protocols/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Protocols/project.json, src/Microsoft.IdentityModel.Tokens/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Tokens/project.json, src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/Properties/AssemblyInfo.cs, src/System.IdentityModel.Tokens.Jwt/project.json, src/System.IdentityModel.Tokens.Saml/Properties/AssemblyInfo.cs, src/System.IdentityModel.Tokens.Saml/project.json
=> RegEx use CultureInvariant

build/VerifySigning.ps1
In this change, we only verify the specific dll in each folder.
=> Remove filePatterns

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/SecurityTokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/ApiChangeTest/ApiChangeTest.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityComparerTests.cs
=>  Made SecurityTokenHandler implement the ISecurityTokenValidator interface

src/Microsoft.IdentityModel.Tokens.Saml/Saml/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSerializer.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/ReferenceSaml.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSerializerTests.cs
=> Solve issue #847, empty AttributeValue support

build/common.props
=> Changed author for nuget packages to Microsoft and added in the package license url

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityComparerTests.cs
=> Added in a null check for the setter of SamlSerializer (in SamlSecurityTokenHandler)

src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityComparerTests.cs
=> Added in a null check in the setter of the Serializer property in Saml2SecurityTokenHandler

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
=> Removed an unnecessary call to ValidateTokenPayload.

src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeySetTests.cs
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/901 
https://github.com/JamesNK/Newtonsoft.Json/issues/703
=> Fix bug in WebKeySet deserialization

src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Xml/DsigSerializer.cs
FxCop is still displaying certain warnings that we want to suppress; a separate task has been created to track that issue.
=> Fixed errors found by FxCop.

src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs, test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
=> The empty JwtHeader() constructor no longer calls into one of the other constructors.

src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj, src/Microsoft.IdentityModel.Tokens/Utility.cs
=> JsonWebKey.CreateECDsa() now throws an exception if called on any operating system other than Windows.

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
Addresses #923.
Also simplified/refactored the Actor test in the JwtSecurityHandlerTests.
=> Added in a flag to control whether or not the InboundClaimTypeMap is used.

src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/CryptoProviderFactoryTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/CustomCryptoProviders.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
=> Added in support for CustomCryptoProvider in the release methods of CryptoProviderFactory

src/Microsoft.IdentityModel.Tokens.Jwt/JsonWebToken.cs, src/Microsoft.IdentityModel.Tokens.Jwt/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Jwt/JwtConstants.cs, src/Microsoft.IdentityModel.Tokens.Jwt/LogMessages.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tests/Microsoft.IdentityModel.Tests.csproj, test/Microsoft.IdentityModel.Tokens.Jwt.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Jwt.Tests/JsonWebTokenTests.cs, test/Microsoft.IdentityModel.Tokens.Jwt.Tests/Microsoft.IdentityModel.Tokens.Jwt.Tests.csproj
=> Added in tests for JsonWebToken and JsonWebTokenHandler, also fixed some bugs in the new APIs

src/Microsoft.IdentityModel.Tokens.Jwt/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
=> Made the exceptions related to JWT signature validation clearer

src/Microsoft.IdentityModel.Tokens.Jwt/JsonWebTokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/References.cs
=> Added in case insensitive comparisons for the 'X5t' and 'KeyId' properties of X509SecurityKeys

src/Microsoft.IdentityModel.Tokens/Validators.cs
Removed unnecessary delegate call
=> Remove duplicate AudienceValidator delegate call

src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs
=> Fixed a race condition in CryptoProviderFactory.CreateSignatureProvider

Wilson.sln, buildConfiguration.xml, src/Microsoft.IdentityModel.Tokens.Extensions/InternalsVisibleTo.cs, src/Microsoft.IdentityModel.Tokens.Extensions/KeyVaultCryptoProvider.cs, src/Microsoft.IdentityModel.Tokens.Extensions/KeyVaultKeyWrapProvider.cs, src/Microsoft.IdentityModel.Tokens.Extensions/KeyVaultSecurityKey.cs, src/Microsoft.IdentityModel.Tokens.Extensions/KeyVaultSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens.Extensions/Microsoft.IdentityModel.Tokens.Extensions.csproj, src/Microsoft.IdentityModel.Tokens.Extensions/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Tokens/InternalsVisibleTo.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultKeyWrapProviderTests.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSecurityKeyAuthenticationCallbackTheoryData.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSecurityKeyConfidentialClientTheoryData.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSecurityKeyManagedServiceIdentityTheoryData.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSecurityKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSecurityKeyTheoryData.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSignatureProviderTests.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultUtilities.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyWrapProviderTheoryData.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/Microsoft.IdentityModel.Tokens.Extensions.Tests.csproj, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/MockKeyVaultClient.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/Properties/AssemblyInfo.cs, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/SignatureProviderTheoryData.cs
The current library provides an extensible model for custom signing and encryption solutions. This makes it possible to create tokens that are backed by cloud-based security keys, such as Azure Key Vault. These changes address #936 and #980 by creating a new extensions project that provides the base implementation to create those types of tokens.
=> Create new M.IM.T.Extensions library to provide crypto operations using cloud-based security keys.

src/Microsoft.IdentityModel.Tokens.Extensions/KeyVaultSecurityKey.cs, src/Microsoft.IdentityModel.Tokens.Extensions/Microsoft.IdentityModel.Tokens.Extensions.csproj, test/Microsoft.IdentityModel.Tokens.Extensions.Tests/KeyVaultSecurityKeyTests.cs
This change removes the Extension library's dependency on ADAL.
=> Remove dependency on ADAL.

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs, src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenTests.cs
=> Included TryGetValue() methods in the JsonWebToken and also made the public methods of JsonWebTokenHandler virtual.

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, src/Microsoft.IdentityModel.JsonWebTokens/TokenValidationResult.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tests/Default.cs
=> Added a CreateClaimsIdentity() method to JsonWebTokenHandler

src/Microsoft.IdentityModel.Tokens.Saml/Saml2/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs
=> Allow easier extending of OneTimeUse condition validation

src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.TestUtils/TheoryDataBase.cs, test/Microsoft.IdentityModel.Tokens.Tests/X509SecurityKeyTests.cs
Reverted back to KeyId as Thumbprint
Added ctor to pass KeyId as needed
Modernized the X509SecurityKey Tests
=> issue #1108

src/Microsoft.IdentityModel.Protocols.WsFederation/WsAddressingConstants.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsUtilityConstants.cs
=> fix WsUtility ns

src/Microsoft.IdentityModel.Logging/Microsoft.IdentityModel.Logging.csproj, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.csproj, src/Microsoft.IdentityModel.Protocols/Microsoft.IdentityModel.Protocols.csproj, src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj, test/Microsoft.IdentityModel.TestUtils/Microsoft.IdentityModel.TestUtils.csproj, test/Microsoft.IdentityModel.Tokens.Tests/Microsoft.IdentityModel.Tokens.Tests.csproj
* Removed unneeded refs from tests
=> Made NS 2.0 adjustments (#1138)

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs, src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.TestUtils/CustomCompressionProviders.cs, test/Microsoft.IdentityModel.TestUtils/JWEDecompressionTheoryData.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
=> Added support for JWE decompression in JwtSecurityTokenHandler

src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs
Addresses #1121.
Please let me know if there's anything else we want to include in this Wiki page:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII
=> Added a link to the PII documentation in the PII logging code

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationTests.cs
=> If OpenIdConnectConfiguration.SigningKeys is an empty collection it is no longer serialized

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.TestUtils/ValidationDelegates.cs
=> Ensured that JsonWebTokenHandler makes use of the issuer returned by the IssuerValidator

runTests.ps1, src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSignatureProvider.cs, test/Microsoft.IdentityModel.Tokens.Tests/CryptoProviderFactoryTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/MultiThreadingTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
=> Set the CacheSignatureProviders property to true by default

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs
=> JsonWebTokenHandler.CreateToken() now adds iat, nbf, and exp as longs not strings

src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs
Improves documentation of behaviour of multiple overlapping claims in JwtPayload and JwtSecurityToken. 
Fixes #1342
=> Improve doc of JwtPayload and JwtSecurityToken re claims

src/Microsoft.IdentityModel.Protocols.WsTrust/WsTrustMessage.cs, src/System.ServiceModel.Federation/WSTrustChannelSecurityTokenProvider.cs, test/System.ServiceModel.Federation.Tests/Mocks/MockRequestChannel.cs, test/System.ServiceModel.Federation.Tests/Mocks/WSTrustChannelSecurityTokenProviderWithMockChannelFactory.cs, test/System.ServiceModel.Federation.Tests/WSTrustChannelSecurityTokenProviderTests.cs
Generate request entropy based on KeyEntropyMode
=> Generate request entropy

buildConfiguration.xml
=> updated version to 6.5.2
