.gitignore, src/Microsoft.IdentityModel.Logging/Microsoft.IdentityModel.Logging.xproj, src/Microsoft.IdentityModel.Protocol.Extensions/Microsoft.IdentityModel.Protocols.xproj, src/Microsoft.IdentityModel.Protocol.Extensions/OpenIdConnectMessage.cs, src/System.IdentityModel.Tokens/System.IdentityModel.Tokens.xproj, tests/Microsoft.IdentityModel.Logging.Tests/Microsoft.IdentityModel.Logging.Tests.xproj, tests/Microsoft.IdentityModel.Protocol.Extensions.Tests/Microsoft.IdentityModel.Protocol.Extensions.Tests.xproj, tests/System.IdentityModel.Tokens.Tests/System.IdentityModel.Tokens.Tests.xproj
Fixup project for dnx.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/115%23discussion_r28101323%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/115%23discussion_r28104193%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/115%23discussion_r28107269%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20d3562b29ac165ea7790bc90515d0f9ba22b48f03%20src/Microsoft.IdentityModel.Protocol.Extensions/OpenIdConnectMessage.cs%205%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/115%23discussion_r28101323%22%2C%20 …
=> import DNX project types

src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, tests/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs
In Windows, JwtPayload.Claims works fine. If a JWT claim has an array of strings, for example, "scope": ["openid", "email", "profiles"], it decomposes them fine. One claim is turned into three.
With Mono however (4.0.1), the claim value is treated as an ArrayList, so it doesn't match IEnumerable and thus falls through to being serialized as JSON.
This PR works on Mono and is pretty simple. I just added a check for the ArrayList type and then mimicked the IEnumerable decomposition.
If it's too big of a change, I'm at least hoping it starts a discussion on how to fix claims for use with Mono.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/161%23issuecomment-105979845%22%2C%2 …
=> JwtPayload.Claims broken in Mono

src/Microsoft.IdentityModel.Protocol.Extensions/Configuration/HttpDocumentRetriever.cs, src/Microsoft.IdentityModel.Protocol.Extensions/Configuration/OpenIdConnectConfigurationRetriever.cs
The double 'await' in HttpDocumentRetriever.cs caused a deadlock.
Introduced new variable 'keys' in OpenIdConnectConfigurationRetriever.cs for clarification.
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/184?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/184'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix for deadlock. Issue #183

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolInvalidAtHashException.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolInvalidStateException.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidationContext.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, src/System.IdentityModel.Tokens/ErrorMessages.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs, test/System.IdentityModel.Tokens.Tests/ExpectedException.cs, test/System.IdentityModel.Tokens.Tests/IdentityUtilities.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/tushargupta51%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/228%23issuecomment-133114964%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-20T18%3A46%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%20e74b59122d7 …
=> Protocol validation

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectMessage.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectParameterNames.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs, src/System.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens/project.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMessageTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs
#256 #258
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/259%23issuecomment-143480280%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/259%23issuecomment-143519877%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/259%23issuecomment-143837662%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/259%23issuecomment-143881812%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/259%23discussion_r40501580%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22 …
=> Fixes issues with oidc protocol validation

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectMessage.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdProviderMetadataNames.cs, src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMessageTests.cs
#266, #276
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/285%23issuecomment-148280458%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/285%23issuecomment-148789911%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/285%23discussion_r42083265%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/9656e93833ae56367b1f2a30caa7d4068dc07f00%23commitcomment-13802676%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/9656e93833ae56367b1f2a30caa7d4068dc07f00%23commitcomment …
=> Rc1 fixes p1

src/Microsoft.IdentityModel.Logging/TextWriterEventListener.cs, src/Microsoft.IdentityModel.Logging/project.json, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/project.json, src/Microsoft.IdentityModel.Protocols.WsFederation/project.json, src/Microsoft.IdentityModel.Protocols/project.json, src/System.IdentityModel.Tokens.Jwt/project.json, src/System.IdentityModel.Tokens.Saml/project.json, src/System.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/System.IdentityModel.Tokens/Utility.cs, src/System.IdentityModel.Tokens/X509SecurityKey.cs, src/System.IdentityModel.Tokens/project.json, test/Microsoft.IdentityModel.Logging.Tests/1d8014ea-c5df-4f95-8b15-233da0682cc3.txt, test/System.IdentityModel.Tokens.Tests/project.json
#288
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/295%23issuecomment-150059020%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/295%23issuecomment-151246152%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/295%23issuecomment-152245750%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/295%23discussion_r42832703%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/295%23discussion_r42911320%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_ur …
=> fixing dispose method

src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.Logging.Tests/testbuild.cmd, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/testbuild.cmd, test/Microsoft.IdentityModel.Protocols.Tests/testbuild.cmd, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/testbuild.cmd, test/Microsoft.IdentityModel.Tokens.Tests/RsaCryptoServiceProviderProxyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/project.json, test/Microsoft.IdentityModel.Tokens.Tests/testbuild.cmd, test/System.IdentityModel.Tokens.Jwt.Tests/testbuild.cmd, test/System.IdentityModel.Tokens.Saml.Tests/testbuild.cmd
1. #353 Removing this workaround since nuget packages are being.
2. #358 : upleveling of rsacsp.
3. Updating testBuild.cmd to run tests for both net451 and netstandardapp1.5
=> Fixing Rsa Upleveling and cleanup

src/Microsoft.IdentityModel.Tokens/SecurityTokenDescriptor.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/End2EndTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityUtilities.cs, test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
Includes Issues:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/363
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/361
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/360
=> SecurityTokenDescriptor uses ClaimsIdentity instead of IEnumerable<Claim>

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectMessage.cs, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectParameterNames.cs, src/System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMessageTests.cs
The OIDC middleware is going to use `sid` soon: https://github.com/aspnet/Security/pull/852. That would be great if we could have a constant for that.
@tushargupta51 @brentschmaltz @polita any chance it could be merged soon? :smile:
=> Add 'sid' to OpenIdConnectMessage/OpenIdConnectParameterNames/JwtRegisteredClaimNames

src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
@tushargupta51 @brentschmaltz 
Addressed #270 by adding static ctors to ConfigurationManager and JwtSecurityTokenHandler. Verified that it emits to logs in Verbose mode.
=> Add assembly version to logs

src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, test/Microsoft.IdentityModel.Tokens.Tests/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
Fixes incorrect disposing of RSA
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/477
=> control when _rsa is disposed

src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
Make `ValidateTokenPayload` usable by `JwtSecurityTokenHandler` implementations
fixes #547
=> Protected ValidateTokenPayload

src/Microsoft.IdentityModel.Protocol.Extensions/SecurityKeyResolver.cs, tests/Microsoft.IdentityModel.Protocol.Extensions.Tests/SecurityTokenHandlerCollectionExtensionsTests.cs
Just added the missing break and two unit tests for #567. The first ValidateToken shows, that the previous implementation was dependent on the order of the Signing Keys.
=> Fix SecurityTokenValidationException during AD FS CertificateRollover

build.ps1
`$clean` like any other input parameter is set to "YES". Presumably the opposite value is expected to be "NO" however the current implementation does not test for "YES" or "NO".
=> Fix $clean handling

README.md
For text to show up on its own line after a list, there has to be a blank line. (Previously the text showed up *within* the list.)
=> Fix newline formatting

.gitignore, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
Refactored GenerateKeyBytes - cut it down half-size.
Renamed tokenString to token for consistency.
Fixed typos.
Renamed variables, made things more consistent. Fixed a bug: added a missing 'virtual' modifier.
Made documentation use <see cref=""> more consistently.
=> Minor documentation fixes

test/Microsoft.IdentityModel.Tests/IdentityComparer.cs
localcontext is now properly merged with the original context before the AreEqual() method terminates.
=> Fixed the bug in IdentityComparer

test/Microsoft.IdentityModel.Tests/IdentityComparer.cs, test/Microsoft.IdentityModel.Tokens.Tests/IdentityComparerTests.cs
Fixes #686.
Instead of adding in a function that compares RsaSecurityKeys, I added the AreRSAParametersEqual() function to the _equalityDict. 
I also modified the BaseType == typeof(System.ValueType) condition so that it also checks whether or not the specific type is located in the dictionary. If it is (such as in the case of RsaParameters), we know that we need to call AreEqual() and not treat the property in the same way that we would treat other properties whose BaseType is a ValueType.
I feel like this makes more sense since the function for RsaSecurityKeys would essentially be CompareAllPublicProperties but with a special case for RSAParameters.
=> Fixed the RsaSecurityKey validation test

src/VerifyResourceUsage.pl
Addresses  #690.
This script checks for:
1) Unused strings in LogMessages.cs
2) Mismatching string IDs and string value prefixes
3) Duplicate IDs across LogMessages.cs files
There is currently some unused code in this script that may need to be modified in order to support checking for incorrect argument count.
=> Added in a perl script to check LogMessages

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationTests.cs
Fixes  #578.
Solved this issue by using conditional property serialization (https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm) to make sure that collections are only serialized if they are non-empty.
=> Added in conditional property serialization for all collections in OpenIdConnectConfiguration

src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, test/Microsoft.IdentityModel.Xml.Tests/DSigSerializerTests.cs
fix issue with empty element
Fixes: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/772
=> ensure we can read keyinfo that we write

src/Microsoft.IdentityModel.Tokens/EpochTime.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs
=> Exception is no longer thrown when a large 'exp' value is encountered

src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs, src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs, src/Microsoft.IdentityModel.Protocols/Configuration/StaticConfigurationManager.cs
Fixes #822.
Changes were only made to classes in the 'src' folder (not the tests).
=> Made sure all exceptions thrown use LogHelper FormatInvariant() for string formatting

src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2Serializer.cs, test/Microsoft.IdentityModel.Tests/ReferenceSaml.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SerializerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSerializerTests.cs
Fixes #815.
Also added in similar tests for SamlSerializer (even though the absolute URI check was not being performed).
=> Saml2Serializer no longer requires NameID to be an absolute URI

src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, test/Microsoft.IdentityModel.Tests/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
Addresses #488. 
The check for valid ECDSA key size has also been moved so that it is done before any bytes are written.
=> Added in logic to ensure the x,y, and d JsonWebKey parameters are the correct size.

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, test/Microsoft.IdentityModel.Tests/ReferenceTheoryData.cs, test/Microsoft.IdentityModel.Tests/ValidationDelegates.cs, test/Microsoft.IdentityModel.Tokens.Tests/ValidatorsTests.cs
Addresses #898.
Previously 'NotBefore' time was used.
=> Made sure ValidateTokenReplay() uses 'NotOnOrAfter' as the token expiration time.

src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtReferenceTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/References.cs
The points on P-521 are 66 bytes, not 64. This is likely a leftover
from being incorrectly referred to as P-512.
Fixes: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/882
=> Correct the P521 keyByteCount in JsonWebKey

src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs
Fixes #884.
Changes made:
- The replacement string for PII in log messages has been shortened.
- The current version, date, and additional information about how to turn PII on/off is now logged before any log messages are written.
=> Changed the PII logging message to make it clearer.

src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/SecurityKey.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtHeaderTests.cs
Addresses #885.
The SecurityKey.KeyId property has been changed to virtual so that JsonWebKey can override it. JsonWebKey now uses the same backing field for its 'KeyId' and 'kid' properties, ensuring that when one changes the other changes as well (ensuring the two properties stay in sync).
=> JsonWebKey 'kid' and 'KeyId' values are now kept in sync.

src/Microsoft.IdentityModel.Tokens.Jwt/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
=> Made sure that token length is never doubled when compared to MaximumTokenSizeInBytes across all SecurityTokenHandlers

src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs, src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtHeaderTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs
Fixes #863.
Changes were made to both the JwtPayload and the JwtHeader classes.
=> Made sure that the GetStandardClaim() method returns null if the value associated with the claimType passed into it is null

src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, test/Microsoft.IdentityModel.Tokens.Tests/TokenValidationParametersTests.cs
Ease addition of custom TokenValidationParameters by utilizing
a Property Bag.
Resolves: #985
See also: #874
=> Add PropertyBag to TokenValidationParameters

src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/Validators.cs, test/Microsoft.IdentityModel.Net45.Tests/Microsoft.IdentityModel.Net45.cs
=> The NotBefore and NotAfter properties of X509Certificates are now checked against local time instead of UTC

src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/LogMessages.cs, src/Microsoft.IdentityModel.Xml/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/LogMessages.cs, src/VerifyResourceUsage.pl
Addresses #989.
Changes made:
- VerifyResourceUsage.pl now ensures that all log message strings are properly formatted. (specifically that all opening braces have a corresponding closing brace)
- The VerifyResourceUsage.pl task on VSTS will now fail if it finds any errors (previously it just printed the errors but still passed).
- Unused log messages have been removed and any mismatches between log message names and their corresponding string values have been fixed.
=> Got rid of unused log messages and added in logic for checking mismatched braces in strings

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs, src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/TokenHandler.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/ApiChangeTest/ApiChangeTest.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenHandlerTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
Addresses #963.
This PR also adds default time setting functionality (during token creation) to the JsonWebTokenHandler.
Exceptions had to be added to the ApiBreakingChangeTest because it does not take base class methods/properties into account.
Also fixes a small typo mentioned in this issue: #999
=> Added in a new abstract TokenHandler class that contains properties shared across all token handlers

src/Microsoft.IdentityModel.Tokens/EncryptingCredentials.cs, src/Microsoft.IdentityModel.Tokens/SecurityAlgorithms.cs, src/Microsoft.IdentityModel.Tokens/X509EncryptingCredentials.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/TestUtilities.cs, test/Microsoft.IdentityModel.Tokens.Tests/EncryptingCredentialsTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/X509EncryptingCredentialsTests.cs
If only a certificate is provided, key wrap encryption algorithm
and data encryption algorithm will be set by default to RsaOaepKeyWrap
and A128CBC-HS256, respectively.
* Add new ctor to EncryptingCredentials to allow users to pass
only a 'shared' symmetric key which will be used to encrypt data, but
it will not be serialized to a SAML token.
* Add internal const strings DefaultAsymmetricKeyWrapAlgorithm and
DefaultSymmetricAlgorithm to indicate the default algorithms used for
key wrap and data encryption
* Add protected ctor to EncryptingCredentials to check if a certificate
passed to X509EncryptedCredentials is null. Provides cleaner stack
trace in case of an exception caused by a null cert.
* Refactor EncryptingCredentials. Move null/empty checks to setters
and provide clearer comments …
=> Add X509EncryptedCredentials class

build/common.props, build/commonTest.props
Addressed _copyright_ as that is the only check that would fail validation.
=> Address NuGet compliance issues

src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs
* This change is only for SAML2 tokens as our current SAML token
support implementation is not validating SubjectConfirmationData.
* NotBefore and NotOnOrAfter are optional elements under
SubjectConfirmationData element (saml-core-2.0 - 2.4.1.2).
* LifetimeValidation of NotBefore and NotOnAfter values should not be
enforced by the library.
Resolves: #1006
=> Remove enforcement of LifetimeValidation for SubjectConfirmationData

src/Microsoft.IdentityModel.Tokens.Saml/Saml2/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs
ValidateConfirmationData is protected virtual method and removing it
represents a breaking change.
Resolves: #1045
=> Add ValidateConfirmationData method back

src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs
Fixes issue that users are facing on non-Windows platforms when using RSACrpytoServiceProvider.
* There is NO support for CspParameters and CspKeyContainerInfo on non-Windows platforms which makes RSACryptoServiceProviderProxy class Windows-specific.
* NETSTANDARD1_4 doesn't not support RSACryptoServiceProvider so there is no need for the proxy.
* Disabled warning _CS0162 Unreachable code detected_ on non-Windows platforms as it's treated as an error during build.
=> Make RSACryptoServiceProviderProxy Windows-specific (#1038)

Tools/apiCompat/baseline/ApiCompatBaseline.netstandard2.0.txt, src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj, src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs, test/Microsoft.IdentityModel.Tokens.Tests/RsaCryptoServiceProviderProxyTests.cs
* RSACryptoServiceProviderProxy is no longer present in netstandard2.0 target, hence the change in ApiCompatBaseline file for netstandard2.0.
* `#if WINDOWS` construct in JsonWebKey class is incorrect as it's a compile-time construct. Support for ECDsa on non-Windows platforms will be provided in #1058.
=> Make RSACryptoServiceProviderProxy available only on Desktop targets

LICENSE.txt, ThirdPartyNotice.txt
* The MIT license doesn't contain a placeholder for "All rights reserved" phrase. Also reformatted the license.
* Added a new file for third party notices
Resolves: #1054
=> Update License and ThirdPartyNotice

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectMessage.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMessageTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeySetTests.cs
* OpenIdConnectMessage constructor exposes JObject
* JsonWebKeySet constructor exposes JsonSerializerSettings
=> Mark JsonWebKeyset and OpenIdConnectMessage constructors as obsolete

Tools/apiCompat/baseline/ApiCompatBaseline.net45.txt, Tools/apiCompat/baseline/ApiCompatBaseline.net451.txt, Tools/apiCompat/baseline/ApiCompatBaseline.net452.txt, Tools/apiCompat/baseline/ApiCompatBaseline.net461.txt, Tools/apiCompat/baseline/ApiCompatBaseline.netstandard1.4.txt, Tools/apiCompat/baseline/ApiCompatBaseline.netstandard2.0.txt, buildConfiguration.xml, src/Microsoft.IdentityModel.Tokens/TokenContext.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationResult.cs
- TokenValidationResult has been moved to M.IM.Tokens from M.IM.JsonWebTokens.
- The version has been bumped to 5.4.0 as moving TokenValidationResult to a different namespace is a breaking change.
=> Moved TokenContext and TokenValidationResult into M.IM.Tokens

build/commonTest.props, src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/SecurityTokenDescriptor.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenTests.cs, test/Microsoft.IdentityModel.TestUtils/Default.cs
- The '_ClaimsIdentity Subject_' property on SecurityTokenDescriptor has been marked as obsolete.
- Also added a new '_Dictionary<string, object> Payload_' property to SecurityTokenDescriptor that will eventually replace the '_ClaimsIdentity Subject_' property.
=> Added a new API to JsonWebTokenHandler that takes in a SecurityTokenDescriptor

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs, test/Microsoft.IdentityModel.Tokens.Tests/X509SecurityKeyTests.cs
Other changes:
- JsonWebTokenHandler now adds the 'x5t' parameter to the header by default if the security key being used is an X509SecurityKey.
- The IdentityComparer can now be used to compare boolean values.
- Fixed some of JsonWebTokenHandler tests that had incorrect TheoryData.
=> Changed the X509SecurityKey.KeyId property so that it's equal to the X5t property

build.ps1, build/apiCompat.props
To enable ApiCompat, '**-runApiCompat**' flag should be included when building (_build -runApiCompat_). The alternative is to set '_RunApiCompat_' property to true.
When disabled, ApiCompat will print-out a message, for each assembly.
When moving to a newer version, baseline files are not relevant anymore.
=> Refine ApiCompat

src/Microsoft.IdentityModel.Protocols.WsFederation/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/Properties/AssemblyInfo.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/QueryHelper.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, test/CrossVersionTokenValidation.Tests/Saml2CrossVersionTokenValidationTests.cs, test/CrossVersionTokenValidation.Tests/SamlCrossVersionTokenValidationTests.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/Microsoft.IdentityModel.Protocols.WsFederation.Tests.csproj, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationMessageTests.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationTestUtilities.cs, test/Microsoft.IdentityModel.Tests/Default.cs, test/Microsoft.IdentityModel.Tests/ReferenceXml.cs, test/Microsoft.IdentityModel.Xml.Tests/EnvelopedSignatureReaderTests.cs
@GeoK 	@mafurman 	
This PR is about successfully validating SAML and SAML2 tokens that were created with "\r\n". This causes issues if the xmlReader used performs xml normalization which collapses "\r\n" into "\n", then signatures fail.
This issue showed up in two places, when obtaining the token from a WaSignin message and SamlSecurityTokenHandlers.
Our WsFederationMessage processing would use an XmlDocument. Some IDP's create the token with "\r\n" that is url-encoded as "%0D%0A", some use create the token with "&#xD;\n" that is url-encoded as "%26%23xD%0A". In either case, the WsFederationMessage.GetToken() would normalize to "\n". Signature failure would occur.
Switching to XmlTextReader using StringReader as the actual reader, fixed this problem.
Unfortunately, .NetStandard 1.4 does …
=> use XmlTextReader, special case netstandard 1.4

src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/VerifyResourceUsage.pl
The following changes have been made to this script:
- Log message usage is now checked across all directories rather than only the directory a particular LogMessages.cs file is located in.
- Public log message IDs are now also checked (previously only internal ones were processed).
- Commented out log message IDs are checked for reuse.
=> Improved VerifyResourceUsage.pl so that it now checks log message usage across all directories

build.ps1
Our local build will now fail if VerifyResourceUsage.pl fails. 
This will make it easier for us to ensure that we have no duplicate, reused, or improperly formatted log message ids.
=> Updated build.ps1 so that VerifyResourceUsage.pl is run at build time

src/Microsoft.IdentityModel.Tokens/SymmetricSignatureProvider.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
Use ""IDX10653: The encryption algorithm '{0}' requires a key size of at least '{1}' bits...."
rather than "IDX10603: Decryption failed. Keys tried: '{0}'...."
=> Fix exception message when key size is too small

build/credscan-exclusion.json
One of the constants in this file has a value of 'client_secret' which triggers a CredScan issue.
Cherry-picked from the dev branch.
=> Updated credscan-exclusion.json to include OpenIdConnectParameterNames

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs
Fixes #1130.
Added two new APIs for encrypting existing JWS tokens, as well as corresponding tests.
=> Added new APIs to JsonWebTokenHandler for encrypting existing JWS tokens

src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtHeaderTests.cs
Fixes #1092.
The 'Alg' header claim is required according to the [JWS RFC](https://tools.ietf.org/html/rfc7515#section-4.1.1), so we should not be allowing the creation of an empty JWT header.
Suggested fix for the 6x release: #1144.
=> JwtHeader default constructor now sets the 'Alg' property to SecurityAlgorithms.None

src/Microsoft.IdentityModel.Xml/DsigSerializer.cs, src/Microsoft.IdentityModel.Xml/LogMessages.cs, test/Microsoft.IdentityModel.TestUtils/TestSets.cs, test/Microsoft.IdentityModel.Xml.Tests/DSigSerializerTests.cs
Transforms can be cpu intensive. By limiting them to 10 or less we reduce the possibility of a DOC attack.
=> Added control for maximum number of transforms in a reference

src/Microsoft.IdentityModel.Logging/Microsoft.IdentityModel.Logging.csproj, src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.csproj, src/Microsoft.IdentityModel.Protocols/Microsoft.IdentityModel.Protocols.csproj, src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj, test/Microsoft.IdentityModel.TestUtils/Microsoft.IdentityModel.TestUtils.csproj, test/Microsoft.IdentityModel.Tokens.Tests/Microsoft.IdentityModel.Tokens.Tests.csproj
Reduce the netstandard 2.0 dependency graph
PS: I'm not sure why **System.Security.Cryptography.Cng** was marked as PrivateAssets="All", that seems broken. I didn't run tests but I installed the packages build to verify the graph was indeed smaller. Hopefully your CI runs tests to verify I didn't break anything 😄
=> Made NS 2.0 adjustments

src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs, src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs, src/Microsoft.IdentityModel.Protocols/LogMessages.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/ConfigurationManagerTests.cs
=> ConfigurationManager no longer throws if _configRetriever fails but _currentConfiguration is not null

src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, test/Microsoft.IdentityModel.Tokens.Tests/CrossTokenTests.cs
=> Reduce DefaultMaximumTokenSizeInBytes from 2MB to 250KB.

src/Microsoft.IdentityModel.Xml/LogMessages.cs
The IDX30100 log message has too many parameters in the format string, causes a formatting error when trying to write the log message.
=> Fix incorrect param count in log message

ThirdPartyNotice.txt, build/common.props
* Added support for generating .snupkg packages that contain .pdb files. As a result, .pdb files are no longer embedded in .nupkg packages.
* Replaced SourceLink.Create.CommandLine with Microsoft.SourceLink.GitHub and updated ThirdPartyNotice file.
* Fixed the '_deprecated PackageLicenseUrl_' issue.
Resolves: #1098
=> Add support for generating separate symbol packages

test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.TestUtils/Default.cs
Some of our tests are failing intermittently because we sometimes generate timestamps on token creation.
Values for the 'exp', 'iat', and 'nbf' claims have been provided for test cases that may fail because of this issue. A test case that was present in the CreateJWS tests (but not CreateJWE) was also added in.
The dev5x branch will also need these changes to be pulled in (along with a similar fix to the CreateJWSUsingSecurityTokenDescriptor tests that is present in dev but not in dev5x).
=> Updated the JsonWebTokenHandlerTests.CreateJWEUsingSecurityTokenDescriptor tests

src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/SupportedAlgorithms.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/AsymmetricSignatureTestData.cs, test/Microsoft.IdentityModel.Tokens.Tests/AsymmetricSignatureTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs
* RSA-PSS support matrix is available [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Supported-Algorithms):
- Rsa-Pss is not available on .NET 4.5 and .NET 4.5.1 targets
- Rsa-Pss is available on .NET 4.6.1 target but only byt Windows CNG
- Rsa-Pss is avaliable on .NET Core on Windows
- Rsa-Pss is available on .NET Core on Unix on SDK versions >= 2.1
* Added new log messages
* Added tests
Resolves: #1117
=>  Add RSA-PSS support

src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/End2EndTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/JsonWebKeySetEnd2EndEC.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests.csproj, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConfigData.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationRetrieverTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMetadataEnd2EndEC.json, test/Microsoft.IdentityModel.TestUtils/DataSets.cs, test/Microsoft.IdentityModel.TestUtils/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeySetTests.cs
* Refactored JsonWebKeySet.GetSigningKeys() method and added support for JWKs with 'kty' = 'EC'.
* Unresolved JsonWebKeys will be skipped by default. `SkipUnresolvedJsonWebKeys` flag controls whether unresolved JsonWebKeys will be included in the resulting collection of GetSigningKeys method.
* Adding only the first certificate from the x5c certificate chain as a SecurityKey.
=> Support JsonWebKeys with the Elliptic Curve key type

src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/End2EndTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/JsonWebKeySetEnd2EndEC.json, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests.csproj, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConfigData.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationRetrieverTests.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectMetadataEnd2EndEC.json, test/Microsoft.IdentityModel.TestUtils/DataSets.cs, test/Microsoft.IdentityModel.TestUtils/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeySetTests.cs
Cherry-picked from the dev5x branch.
Had a couple of conflicts, hence the PR.
Conflicts were in these files:
```
src/Microsoft.IdentityModel.Tokens/LogMessages.cs (one log message removed and one edited)
src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs (constructor that takes Newtonsoft.Json object in 5x)
test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeySetTests.cs (related to the JsonWebKeySet constructor)
```
---
* Refactored JsonWebKeySet.GetSigningKeys() method and added support
for JWKs with 'kty' = 'EC'.
* Unresolved JsonWebKeys will be skipped by default.
SkipUnresolvedJsonWebKeys flag controls whether unresolved JsonWebKeys
will be included in the resulting collection of GetSigningKeys method.
* Adding only the first certificate from the x5c certificate chain as a …
=> Support JsonWebKeys with the Elliptic Curve key type (#1143)

src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityToken.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenTests.cs
Addresses #1185.
I also added in tests that ensure the default values are what we expect.
I'm not sure how much tolerance we should have when comparing DateTime values, so suggestions on that would be appreciated.
=> The default SamlSecurityToken constructor now sets the Assertion property

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenTests.cs
Addresses #1169.
Changes made:
- Added GetClaim() and TryGetClaim() methods to JsonWebToken (as well as associated tests).
- Added logic to retrieve a Claim from the GetPayloadValue() and TryGetPayloadValue() methods.
- Added in tests comparing the GetClaim()/TryGetClaim() versus the GetPayloadValue<Claim>()/TryGetPayloadValue<Claim>() methods.
- Some minor formatting changes.
=> Added GetClaim() and TryGetClaim() methods to JsonWebToken

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
Addresses #1132.
The 'IDX10501' exception message has been modified so that any exceptions that were previously caught during signature validation are now included in it.
There are cases where 'exceptionStrings' is empty, in which case this modification doesn't actually end up providing any extra information for the user. It might make sense to have a separate log message without this parameter for that case.
=> Added an extra parameter for 'exceptionStrings' in IDX10501

src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs, test/Microsoft.IdentityModel.Protocols.Tests/AuthenticationProtocolMessageTests.cs, test/Microsoft.IdentityModel.Protocols.WsFederation.Tests/WsFederationMessageTests.cs
Addresses #1178.
A script hash can be used in a CSP in order to indicate whether a particular JavaScript script is allowed to run. By providing the string representation of the script we're using, we can make it easier for users to obtain this value.
I also refactored AuthenticationProtocolMessageTests.Defaults() to make use of CompareContext.
=> Added a property to AuthenticationProtocolMessage that returns the script used in the post string

src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs, src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/InMemoryCryptoProviderCache.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeyConverter.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SecurityKey.cs, src/Microsoft.IdentityModel.Tokens/SupportedAlgorithms.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSecurityKey.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, src/Microsoft.IdentityModel.Xml/EnvelopedSignatureWriter.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/End2EndTests.cs, test/Microsoft.IdentityModel.TestUtils/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/AsymmetricSignatureTestData.cs, test/Microsoft.IdentityModel.Tokens.Tests/ECDsaAdapterTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeyConverterTest.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeySetTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeyTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/MultiThreadingTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/RsaKeyWrapProviderTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/X509SecurityKeyTests.cs
Moved converting JsonWebKey to a usable SecurityKey to single location
Convert JsonWebKey before checking key details such as KeySize
Maintain a singleton ECDAdapter
When creating cacheKey use internalId if keyid is null or empty
Use default CryptoProviderFactory on SecurityKey rather than create new one
=> JsonWebKey and Related fixes.

src/Microsoft.IdentityModel.Xml/DelegatingXmlDictionaryWriter.cs, src/Microsoft.IdentityModel.Xml/EnvelopedSignatureReader.cs, src/Microsoft.IdentityModel.Xml/EnvelopedSignatureWriter.cs, src/Microsoft.IdentityModel.Xml/XmlTokenStreamReader.cs, src/Microsoft.IdentityModel.Xml/XmlTokenStreamWriter.cs, test/Microsoft.IdentityModel.TestUtils/KeyingMaterial.cs, test/Microsoft.IdentityModel.Xml.Tests/EnvelopedSignatureTheoryData.cs, test/Microsoft.IdentityModel.Xml.Tests/EnvelopedSignatureWriterTests.cs
* Use InnerWriter to write canonical bytes (without signature).
* Use InternalWriter to write non-canonical xml (including signature).
* When WriteSignature() method is called, write only a placeholder signature element using InternalWriter.
* After writing the last (end) element, create XmlTokenStream out of the InternalWriter's stream and write that XmlTokenStream into the original writer. When writing the XmlTokenStream, replace signature [placeholder] element with the real signature (using DSigSerializer). This behavior is followed only if WriteSignature method was invoked explicitly. Otherwise, the default behavior is to generate the signature at the end and to write it directly to the original stream.
* Improve EnvelopedSignatureReader and XmlTokenStreamReader to allow reading an …
=> Support Signature as an inner element with EnvelopedSignatureWriter

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/CompressionProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/DeflateCompressionProvider.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs
Use StringComparison settings where applicable.
Set DtdProcessing.Prohibit when creating XmlReaders where possible.
=> Internal string formatting cleanup

src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs, src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs, src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/JsonWebKeyConverter.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs, src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs, test/Microsoft.IdentityModel.KeyVaultExtensions.Tests/Microsoft.IdentityModel.KeyVaultExtensions.Tests.csproj, test/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.Tests/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.Tests.csproj, test/Microsoft.IdentityModel.TestUtils/KeyingMaterial.cs, test/Microsoft.IdentityModel.Tokens.Tests/AsymmetricSignatureTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/JsonWebKeyConverterTest.cs, test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
We want to use JsonWebKeyConveter when converting from a JsonWebKey.
This provides some consistency.
We also noticed that there was some cleanup possible in the JsonWebKeyConverter tests.
We also included #ifdef for Netstandard2.0 for X509SecurityKey when obtaining private and public keys
This address issues: 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1221
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1222
=> Use JsonWebKeyConvertor consistently

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs, src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/SecurityTokenDescriptor.cs, src/Microsoft.IdentityModel.Tokens/json/JsonConvert.cs, src/Microsoft.IdentityModel.Tokens/json/JsonPosition.cs, src/Microsoft.IdentityModel.Tokens/json/Linq/JContainer.Async.cs, src/Microsoft.IdentityModel.Tokens/json/Linq/JContainer.cs, src/Microsoft.IdentityModel.Tokens/json/Linq/JObject.cs, src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs, test/Microsoft.IdentityModel.TestUtils/Default.cs
Fixes #1193.
If both SecurityTokenDescriptor.Subject and SecurityTokenDescriptor.Claims are set, both are used when creating a JWT token. However, if duplicate values are present, the ones found in SecurityTokenDescriptor.Claims will override those found in SecurityTokenDescriptor.Subject.
=> JWT tokens can now be created from both SecurityTokenDescriptor.Subject and SecurityTokenDescriptor.Claims

build/cgmanifest.json
Since Wilson 6.x uses Newtonsoft.JSON internally, the Component Governance tool is unable to automatically detect it. Because of this, it must be manually registered as open source in the cgmanifest.json file.
=> Added a cgmanifest.json file that specifies the internal Newtonsoft.JSON version that we're using

src/Microsoft.IdentityModel.JsonWebTokens/JwtRegisteredClaimNames.cs, src/System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.cs
Work on issue #1125 
@brentschmaltz 
Changing link references in comments is easiest way to keep up with standard.
Especially since Actort claims needs to be there for backwards compatibility.
Esentially, only code docs are changed
=> Sync JWT claim names with current RFC7519 standard and OpenID Connect 1.0 standard

src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs
Modified the code slightly to include an explicit setting for turning off DtdProcessing.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1269
=> Add DtdProcessing.Prohibit explicitly when creating a xmlReader

build.ps1, src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs
When RSACryptoServiceProviderProxy creates a new RSA instance it should be disposed.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1240
=> RSACryptoServiceProviderProxy should call RSA.Dispose() if a instance was created.

src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConfigData.cs, test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationTests.cs
=> OpenIdConnectConfiguration.SigningKeys property is no longer used during deserialization

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs, src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs, src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs, test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenTests.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs
Currently, claims created from a deserialized JSON string might have 'System.DateTime' (invalid claim type) or ClaimValueTypes.String type, depending on the format of a datetime json string, the way how JSON string was deserialized, and json handler being used.
This PR changes fixes this inconsistency, so claims that hold DateTime values in ISO8061 datetime format will have ClaimValueTypes.DateTime as a claim value type. DateTime strings represented in datetime formats other than ISO8061 will have ClaimValueTypes.String as a claim value type.
Also, by default, Newtonsoft.JSON serializer encloses some DateTime strings with quotes which results in ""dateTimeValue"" (see #1261). This behavior is changed, so that resulting string doesn't contain the
double quotes.
DateTime claim value …
=> Fix DateTime claims processing

src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs, test/Microsoft.IdentityModel.Protocols.Tests/AuthenticationProtocolMessageTests.cs
Fixes #1263.
Also modified the setters for the other public properties on `AuthenticationProtocolMessage` so that if an `ArgumentNullException` is thrown it includes the name of the property (not just "value").
NOTE: `LogHelper.LogArgumentNullException()` uses the following message:
`"IDX10000: The parameter '{0}' cannot be a 'null' or an empty object."`
This doesn't really make sense for the properties on this class since they can be empty strings. 
Should another log message be added that's just "the parameter cannot be null"?
=> Added a setter for the AuthenticationProtocolMessage.Script property

build/VerifySigning.ps1
* The script now tries to find sn.exe files and signtool.exe in defined paths first. If any of the files is not found, the script will fallback to its previous behavior (recursively searching for sn.exe and signtool.exe in C:\Program Files(x86)).
* Fixed authenticode signature verification.
=> Fix VerifySigning script

src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, src/Microsoft.IdentityModel.Tokens/Validators.cs, test/Microsoft.IdentityModel.TestUtils/ReferenceTheoryData.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/Saml2SecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/SamlSecurityTokenHandlerTests.cs, test/Microsoft.IdentityModel.Tokens.Saml.Tests/ValidateTheoryData.cs, test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs
Fixes #1100.
Ex. `TokenValidationParameters.AudienceValidator` is called before the value of `TokenValidationParameters.ValidateAudience` is checked.
=> Validators call delegates before checking if validation should occur

build.ps1, src/Microsoft.IdentityModel.Logging/LogHelper.cs, src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs, src/Microsoft.IdentityModel.Tokens/Validators.cs, test/Microsoft.IdentityModel.Tokens.Tests/TokenValidationParametersTests.cs, test/Microsoft.IdentityModel.Tokens.Tests/ValidatorsTests.cs
It is common for '/' to show up at the end of the audience.
From a security standpoint, this is not meaningful, we added support for ignoring such slash's.
Issue: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1273
=> Ignore single ending slash when validating audience

NuGet.Config, build.ps1
This PR has two small items.
1. Checking the environment variable for the installation path to Visual Studio and setting the msbuildDir variable from that.
2. Adding '< / clear>' in nuget.config. This ensures that our build will use a controlled set of packages.
=> check for VSINSTALLDIR and adjust path for msbuild.exe

src/Microsoft.IdentityModel.Protocols.WsTrust/WsTrustSerializer.cs, test/Microsoft.IdentityModel.Protocols.WsTrust.Tests/WsTrustTests.cs
Small fixes to how `WsTrustSerializer` handles ProofEncryption and empty unknown elements which were causing test failures.
Work is still needed to add serialization/deserialization support for SecurityKeys but this addresses some issues with the `<ProofEncryption>` element itself and gets tests passing.
=> ProofEncryption fix-up

src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs, src/Microsoft.IdentityModel.JsonWebTokens/LogMessages.cs, src/Microsoft.IdentityModel.Protocols.SignedHttpRequest/SignedHttpRequestHandler.cs, src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs, src/Microsoft.IdentityModel.Tokens/LogMessages.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.Protocols.SignedHttpRequest.Tests/SignedHttpRequestE2ETests.cs, test/Microsoft.IdentityModel.Protocols.SignedHttpRequest.Tests/SignedHttpRequestTestUtils.cs
Fixes the issues below.
We do not want to cache SignatureProviders for SignedHttpRequests as the belief is these will be used, particularly when verifying, infrequently.
We do not need or want to put a kid into the SignedHttpRequest as we should be relying on the cnf claim or extensibility.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1352
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1351
Some formatting and error messages were modified.
=> Fixes for issues:

src/Microsoft.IdentityModel.Protocols.WsTrust/WsTrustMessage.cs, src/System.ServiceModel.Federation/WSTrustChannelSecurityTokenProvider.cs, src/System.ServiceModel.Federation/WsFederationBindingElement.cs, src/System.ServiceModel.Federation/WsFederationHttpBinding.cs, src/System.ServiceModel.Federation/WsTrustChannelClientCredentials.cs, src/System.ServiceModel.Federation/WsTrustChannelSecurityTokenManager.cs, test/System.ServiceModel.Federation.Tests/Mocks/WSTrustChannelSecurityTokenProviderWithMockChannelFactory.cs, test/System.ServiceModel.Federation.Tests/ReflectionHelpers.cs, test/System.ServiceModel.Federation.Tests/WSTrustChannelSecurityTokenProviderTests.cs, test/System.ServiceModel.Federation.Tests/WsFederationHttpBindingTests.cs, test/System.ServiceModel.Federation.Tests/WsFederationHttpBindingTheoryData.cs
This adds a `WSTrustContext` property to both `WsFederationHttpBinding` and `WsFederationHttpBindingElement` and pipes those values through to `WsTrustChannelClientCredentials`, so that it will be used as the `RequestContext` in `WSTrustChannelSecurityTokenProvider`.
=> Get RequestContext from WsFederationHttpBinding

build/dependencies.props, src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs, src/Microsoft.IdentityModel.Tokens/Encryption/AuthenticatedEncryptionProvider.cs, src/Microsoft.IdentityModel.Tokens/SymmetricSignatureProvider.cs, src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs, test/Microsoft.IdentityModel.TestUtils/DerivedTypes.cs, test/Microsoft.IdentityModel.Tokens.Tests/AuthenticatedEncryptionProviderTests.cs
These changes address signature providers adding memory pressure.
We do not cache SignatureProviders by default that are used by the AuthenticationEncryptionProvider.
If this is needed, then users will need to use extensibility from keys.
Tests have been added to show how to do this.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1357
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1292
=> Fixes for issues relating to Authenticated Encryption and Caching

src/System.ServiceModel.Federation/System.ServiceModel.Federation.csproj, src/System.ServiceModel.Federation/WSTrustChannelSecurityTokenProvider.cs, test/System.ServiceModel.Federation.Tests/Mocks/WSTrustChannelSecurityTokenProviderWithMockChannelFactory.cs, test/System.ServiceModel.Federation.Tests/WSTrustChannelSecurityTokenProviderTests.cs
We should add back fuller cache support (including using `IDistributedCache`) in the future
if/when caches can be shared between providers. With the current API surface area, though,
there's no way for a given `WSTrustChannelSecurityTokenProvider` to use more than one RST,
so it will only ever have to cache a single response. Given that, the design that we had here
was more complicated and slower than it needed to be.
=> Simplify caching since a token provider will always use the same RST

src/System.ServiceModel.Federation/WSTrustChannelSecurityTokenProvider.cs, test/System.ServiceModel.Federation.Tests/MessageSecurityVersionTheoryData.cs, test/System.ServiceModel.Federation.Tests/Mocks/MockRequestChannel.cs, test/System.ServiceModel.Federation.Tests/Mocks/MockRequestChannelFactory.cs, test/System.ServiceModel.Federation.Tests/Mocks/WSTrustChannelSecurityTokenProviderWithMockChannelFactory.cs, test/System.ServiceModel.Federation.Tests/ProviderCachingTheoryData.cs, test/System.ServiceModel.Federation.Tests/WSTrustChannelSecurityTokenProviderTests.cs, test/System.ServiceModel.Federation.Tests/WSTrustTestHelpers.cs
This updates `WSTrustChannelSecurityTokenProvider` to get message security version from the issuer binding's security binding element or from the issued token parameter's default message security version. One question is where the issuer binding should be retrieved from. This change gets the issuer binding from the incoming security token requirement (which is where it came from in NetFx). Other code paths in WSTrustChannelSecurityTokenProvider (such as `CreateChannelFactory`) get the issuer binding from issued token parameters, though. We should review whether there's a reason to get the binding from these different sources and, if not, standardize on one input.
This PR also fixes a small bug that was introduced when the token provider's "is unexpired" method was changed to "is expired". …
=> Consider WsTrust version when issuing tokens

src/System.ServiceModel.Federation/WsFederationBindingElement.cs, src/System.ServiceModel.Federation/WsTrustChannelClientCredentials.cs, src/System.ServiceModel.Federation/WsTrustChannelSecurityTokenManager.cs, test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs, test/Microsoft.IdentityModel.TestUtils/Microsoft.IdentityModel.TestUtils.csproj, test/System.ServiceModel.Federation.Tests/ClientCredentialsTheoryData.cs, test/System.ServiceModel.Federation.Tests/ClientCredentialsWrappingTests.cs
Fixed the Clone method
Create new instance of WsTrustChannelClientCredentials and wrap when only ClientCredentials  is available.
Defer to wrapped ClientCredentials when non-WSTrust token is being requested
Clone WsTrustChannelClientCredentials  when passing to security token manager
=> Improve credentials class handling
